modules:
  - shared
  - jvm
  - ktor
  - native/linux
  - native/macos
  - native/windows
  - compose
  - plugins/build-config
# - web/js
# - web/wasm
# - web/wasi
# - "*-cli"

plugins:
  - ./plugins/build-config
