modules:
  - shared
  - jvm/app
  - jvm/compose
  - jvm/ktor
  - native/linux
  - native/macos
  - native/windows
  - plugins/build-config
# - web/js
# - web/wasm
# - web/wasi
# - "*-cli"

plugins:
  - ./plugins/build-config
