name: 🔨 Build & Release

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - LICENSE
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AMPER_BOOTSTRAP_CACHE_DIR: ${{ github.workspace }}/.amper/boot-cache
  AMPER_CACHE_ROOT: ${{ github.workspace }}/.amper/shared-cache

jobs:
  build:
    name: 🔨 Build
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: ⚡ Cache Amper bootstrap
        uses: actions/cache@v5
        with:
          path: ${{ env.AMPER_BOOTSTRAP_CACHE_DIR }}
          key: amper-boot-${{ runner.os }}-${{ hashFiles('amper', 'amper.bat') }}

      - name: 📦 Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.AMPER_CACHE_ROOT }}/.m2.cache
            ${{ env.AMPER_CACHE_ROOT }}/kotlin
          key: amper-shared-deps-${{ hashFiles('project.yaml', '**/module.yaml', '**/plugin.yaml', 'amper', 'amper.bat', 'libs.versions.toml') }}
          restore-keys: |
            amper-shared-deps-

      - name: 🛠️ Cache toolchains & JDKs
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.AMPER_CACHE_ROOT }}/download.cache
            ${{ env.AMPER_CACHE_ROOT }}/extract.cache
          key: amper-shared-downloads-${{ runner.os }}-${{ hashFiles('project.yaml', '**/module.yaml', '**/plugin.yaml', 'amper', 'amper.bat', 'libs.versions.toml') }}
          restore-keys: |
            amper-shared-downloads-${{ runner.os }}-

      - name: 🗂️ Cache build outputs
        uses: actions/cache@v5
        with:
          path: |
            build/*
            !build/logs
          key: amper-project-${{ runner.os }}-${{ hashFiles('project.yaml', '**/module.yaml', '**/plugin.yaml', 'amper', 'amper.bat', 'libs.versions.toml') }}
          restore-keys: |
            amper-project-${{ runner.os }}-

      - name: 🏗️ Build release
        id: amper-build
        run: |
          ./amper build -v release
          ./build/tasks/_macos_linkMacosArm64Release/macos.kexe

      - name: ☕ Upload app-jvm
        if: steps.amper-build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: app-jvm.jar
          path: build/tasks/_app_jarJvm/app-jvm.jar
          archive: false
          if-no-files-found: error

      - name: 🐧 Upload linux-x64
        if: steps.amper-build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: app-linux-x64.zip
          path: build/tasks/_linux_linkLinuxX64Release/linux.kexe
          if-no-files-found: error

      - name: 🐧 Upload linux-arm64
        if: steps.amper-build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: app-linux-arm64.zip
          path: build/tasks/_linux_linkLinuxArm64Release/linux.kexe
          if-no-files-found: error

      - name: 🍎 Upload macos-arm64
        if: steps.amper-build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: app-macos-arm64.zip
          path: build/tasks/_macos_linkMacosArm64Release/macos.kexe
          if-no-files-found: error

      - name: 🪟 Upload windows-x64
        if: steps.amper-build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: app-windows-x64.zip
          path: build/tasks/_windows_linkMingwX64Release/windows.exe
          if-no-files-found: error
